language: node_js
node_js:
- 0.10
deploy:
  provider: npm
  email: ryanbbillingsley@gmail.com
  api_key:
    secure: Qgbn3utIdeoHirKNyWJ+qopZbY2QtxFd1+ry1Kbt0PAUEumY5kDgLIECXQbO/hAaT3AQ2EFNOVyotoCOjZVF0HgXf57zqNHlh5xsqm/U4pjEdUsZHeg9WDHFWmCuslzUuS8thX7hR6QndnANy566lUEW3ZuHtOd6Zo7NAWmzkNs=
  on:
    tags: true
    all_branches: true
    repo: baminteractive/node-ipfilter
